# NOTE: This file was auto-generated by SpeedySVCService, 
#       and it's usually best not to modify it directly
from typing import Union, List, Tuple
from speedysvc.SpeedySVCClient import SpeedySVCClient
from speedysvc.compression.compression_types import snappy_compression


class TestServiceClient(SpeedySVCClient):
    def __init__(self,
                 address: Union[List, Tuple, str] = "shm://test_server_methods:5535",
                 use_spinlock: bool = True,
                 use_in_process_lock: bool = True,
                 compression_inst=snappy_compression):
        SpeedySVCClient.__init__(self, address, use_spinlock, use_in_process_lock, compression_inst)
        
    def test_defaults(self, data, default='test'):
        return self._call_remote(JSONSerialisation,
                                 JSONSerialisation, 
                                 b"test_defaults", 
                                 (data, default,),
                                 None,
                                 None)
        
    def test_json_echo(self, data):
        return self._call_remote(JSONSerialisation,
                                 JSONSerialisation, 
                                 b"test_json_echo", 
                                 (data,),
                                 None,
                                 None)
        
    def test_json_echo_iterator(self, data):
        return self._iter_remote(JSONSerialisation,
                                 JSONSerialisation, 
                                 b"test_json_echo_iterator", 
                                 (data,),
                                 None,
                                 None)
        
    def test_marshal_echo(self, data):
        return self._call_remote(MarshalSerialisation,
                                 MarshalSerialisation, 
                                 b"test_marshal_echo", 
                                 (data,),
                                 None,
                                 None)
        
    def test_msgpack_method(self, data):
        return self._call_remote(MsgPackSerialisation,
                                 MsgPackSerialisation, 
                                 b"test_msgpack_method", 
                                 (data,),
                                 None,
                                 None)
        
    def test_pickle_echo(self, data):
        return self._call_remote(PickleSerialisation,
                                 PickleSerialisation, 
                                 b"test_pickle_echo", 
                                 (data,),
                                 None,
                                 None)
        
    def test_raw_echo(self, data: bytes):
        return self._call_remote_raw(RawSerialisation,
                                     RawSerialisation,
                                     b"test_raw_echo",
                                     data)
        
    def test_raw_return_len(self, data: bytes):
        return self._call_remote_raw(RawSerialisation,
                                     RawSerialisation,
                                     b"test_raw_return_len",
                                     data)
        

from speedysvc.serialisation.JSONSerialisation import JSONSerialisation
from speedysvc.serialisation.MarshalSerialisation import MarshalSerialisation
from speedysvc.serialisation.MsgPackSerialisation import MsgPackSerialisation
from speedysvc.serialisation.PickleSerialisation import PickleSerialisation
from speedysvc.serialisation.RawSerialisation import RawSerialisation
