LEncodings = \
    [['all languages', 'utf_16'], 
    ['all languages', 'utf_7'], 
    ['all languages', 'utf_8'], 
    ['all languages (BMP only)', 'utf_16_be'], 
    ['all languages (BMP only)', 'utf_16_le'], 
    ['Arabic', 'cp1256'], 
    ['Arabic', 'cp864'], 
    ['Arabic', 'iso8859_6'], 
    ['Baltic languages', 'cp1257'], 
    ['Baltic languages', 'cp775'], 
    ['Baltic languages', 'iso8859_13'], 
    ['Baltic languages', 'iso8859_4'], 
    ['Bulgarian, Byelorussian, Macedonian, Russian, Serbian', 'cp1251'], 
    ['Bulgarian, Byelorussian, Macedonian, Russian, Serbian', 'cp855'], 
    ['Bulgarian, Byelorussian, Macedonian, Russian, Serbian', 'iso8859_5'], 
    ['Bulgarian, Byelorussian, Macedonian, Russian, Serbian', 'mac_cyrillic'], 
    ['Canadian', 'cp863'], 
    ['Celtic languages', 'iso8859_14'], 
    ['Central and Eastern Europe', 'cp1250'], 
    ['Central and Eastern Europe', 'cp852'], 
    ['Central and Eastern Europe', 'iso8859_2'], 
    ['Central and Eastern Europe', 'mac_latin2'], 
    ['Danish, Norwegian', 'cp865'], 
    ['English', 'ascii'], 
    ['English', 'cp037'], 
    ['English', 'cp437'], 
    ['Esperanto, Maltese', 'iso8859_3'], 
    ['Greek', 'cp1253'], 
    ['Greek', 'cp737'], 
    ['Greek', 'cp869'], 
    ['Greek', 'cp875'], 
    ['Greek', 'iso8859_7'], 
    ['Greek', 'mac_greek'], 
    ['Hebrew', 'cp1255'], 
    ['Hebrew', 'cp424'], 
    ['Hebrew', 'cp856'], 
    ['Hebrew', 'cp862'], 
    ['Hebrew', 'iso8859_8'], 
    ['Icelandic', 'cp861'], 
    ['Icelandic', 'mac_iceland'], 
    ['Japanese', 'cp932'], 
    ['Japanese', 'euc_jis_2004'], 
    ['Japanese', 'euc_jisx0213'], 
    ['Japanese', 'euc_jp'], 
    ['Japanese', 'iso2022_jp'], 
    ['Japanese', 'iso2022_jp_1'], 
    ['Japanese', 'iso2022_jp_2004'], 
    ['Japanese', 'iso2022_jp_3'], 
    ['Japanese', 'iso2022_jp_ext'], 
    ['Japanese', 'shift_jis'], 
    ['Japanese', 'shift_jis_2004'], 
    ['Japanese', 'shift_jisx0213'], 
    ['Japanese, Korean, Simplified Chinese, Western Europe, Greek', 'iso2022_jp_2'], 
    ['Kazakh', 'ptcp154'], 
    ['Korean', 'cp949'], 
    ['Korean', 'euc_kr'], 
    ['Korean', 'iso2022_kr'], 
    ['Korean', 'johab'], 
    ['Nordic languages', 'iso8859_10'], 
    ['Portuguese', 'cp860'], 
    ['Russian', 'cp866'], 
    ['Russian', 'koi8_r'], 
    ['Simplified Chinese', 'gb2312'], 
    ['Simplified Chinese', 'hz'], 
    ['Thai', 'cp874'], 
    ['Traditional Chinese', 'big5'], 
    ['Traditional Chinese', 'big5hkscs'], 
    ['Traditional Chinese', 'cp950'], 
    ['Turkish', 'cp1026'], 
    ['Turkish', 'cp1254'], 
    ['Turkish', 'cp857'], 
    ['Turkish', 'iso8859_9'], 
    ['Turkish', 'mac_turkish'], 
    ['Ukrainian', 'koi8_u'], 
    ['Unified Chinese', 'gb18030'], 
    ['Unified Chinese', 'gbk'], 
    ['Urdu', 'cp1006'], 
    ['Vietnamese', 'cp1258'], 
    ['West Europe', 'latin_1'], 
    ['Western Europe', 'cp1140'], 
    ['Western Europe', 'cp1252'], 
    ['Western Europe', 'cp500'], 
    ['Western Europe', 'cp850'], 
    ['Western Europe', 'iso8859_15'], 
    ['Western Europe', 'mac_roman']
]
